# Generated by Django 6.0.6 on 2026-06-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_card_last4_order_cash_tendered_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('void_passcode', models.CharField(default='1234', max_length=20)),
            ],
        ),
    ]
